version: '3.8'

services:
  app:
    build: .
    container_name: springboot_grupo19
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/recomendacion2?sslmode=disable&connectionTimeout=30000
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres.99
      SERVER_PORT: 8099
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8099:8099"
    restart: unless-stopped
    entrypoint: ["sh", "-c", "sleep 30 && java -jar app.jar"]

  db:
    image: postgres:15
    container_name: postgres_grupo19
    environment:
      POSTGRES_DB: recomendacion2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres.99
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
