  version: '3.8'

  services:
    app:
      build: .
      container_name: springboot_grupo19
      depends_on:
        db:
          condition: service_healthy
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres?sslmode=disable&connectionTimeout=30000
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: ronnie
        SERVER_PORT: 9091
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_JPA_SHOW_SQL: "true"
      ports:
        - "9091:9091"
      restart: unless-stopped
      entrypoint: ["sh", "-c", "sleep 30 && java -jar app.jar"]

    db:
      image: postgres:15
      container_name: postgres_grupo19
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ronnie
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
